### ISSUE TITLE
Polymorphism

### ISSUE THREAD

**Issue by lrvldot** [WackyStudio/build-an-api-with-laravel#51]
Hey guys
I wanted to know if this lib can manage polymorphism?
Have a great day

**Comment by lrvldot** [comment]
(I did buy the book btw :))

**Comment by ThomasNoergaard** [comment]
Hey @lrvldot 

Sorry for the late answer.

Could you elaborate a bit more, do you mean polymorphic relations?

**Comment by lrvldot** [comment]
Yes exactly, I am asking about polymorphic relations.
Does the code handle this part or do I have to implement it ? :)

**Comment by ThomasNoergaard** [comment]
Unfortunately we're not covering polymorphic relations in the book. 
But the way the API is implemented you should in theory be able to use polymorphic relations, or implement these fairly easy, since Laravel is doing the heavy lifting in this part.

**Comment by lrvldot** [comment]
Thanks for the response. I'll try to do it

**Comment by ThomasNoergaard** [comment]
You're welcome @lrvldot :)
